### ISSUE TITLE
Lib don't work on ESP8266 Arduio 

### ISSUE THREAD

**Issue by e1970180** [FrankBoesing/FastCRC#10]
Dear Frank,

Would you please make possible to use you great lib on ESP82266 also?

I propose it could be done by changing header file from 
       #include <avr/pgmspace.h>
 to something like this:
#ifdef __AVR__
	#include <avr/pgmspace.h>
#elif defined(ESP8266)
	#include <pgmspace.h>
#endif

 Thanks in advance!

**Comment by FrankBoesing** [comment]
https://github.com/FrankBoesing/FastCRC/commit/93869422f2dbfbc5429ea7f5db3b8b0293688844

Thanks :)
