### ISSUE TITLE
Add to PlatformIO libraries

### ISSUE THREAD

**Issue by dontsovcmc** [FrankBoesing/FastCRC#14]
Please, add your library to Platformio. Thanks!

**Comment by FrankBoesing** [comment]
how?

**Comment by dontsovcmc** [comment]
It's very easy:
https://docs.platformio.org/en/latest/librarymanager/config.html

library.json for platformio 
library.properties for Arduino 1.5.x
see example here: https://platformio.org/lib/show/993/MegunoLink/manifest
another lib: [wifimanager](https://github.com/tzapu/WiFiManager/blob/master/library.json)
register it: https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html

**Comment by FrankBoesing** [comment]
Thanks :)
Got the message: "The library has been successfully registered and is waiting for moderation"
