### ISSUE TITLE
support buffers larger than 64K

### ISSUE THREAD

**Issue by manitou48** [FrankBoesing/FastCRC#15]
Not real critical, but I noticed I couldn't do CRC on buffer larger than 64KB, because benchmark and library uses uint16_t for datalen.  It will be a bit messy to change all of those to uint32_t 

whatever.

**Comment by GitMoDu** [comment]
The 8 bit micros really don't like to handle uint32_t, maybe it's something that should be done with a #define?

**Comment by FrankBoesing** [comment]
sizeof(int) could help to indentify 8 bit micros.
Manitou, can you add a pull request ?

**Comment by bxparks** [comment]
Drive-by comment: On 8-bit AVR processors, `sizeof(size_t) == 2`. So it's probably best to break up the long array into chunks smaller than 64kB and call the `xxx_upd()` functions multiple times.

**Comment by FrankBoesing** [comment]
Or just drop 8 Bit support..

**Comment by bxparks** [comment]
Totally fair, it's your library.

Since `sizeof(size_t)` cannot be used in a `#if` macro, you can probably do something like this:

```c++
#if defined(ARDUINO_ARCH_AVR) || defined(ARDUINO_ARCH_MEGAAVR)
  #error 8-bit processors not supported
#endif
```

I don't know what other 8-bit processors are out there supporting the Arduino framework.

**Comment by FrankBoesing** [comment]
Sorry for the *very* long delay.
I've added a branch that just uses size_t (16 BIT on 8-Bit AVR, 32 Bit else)

What do you think?

**Comment by FrankBoesing** [comment]
Merged branch to main.
