### ISSUE TITLE
The "kermit" method does not match the lammertbies

### ISSUE THREAD

**Issue by Eitol** [FrankBoesing/FastCRC#16]
FastCRC16 CRC16;

void setup() {
    String buf = "123456789";
    Serial.begin(9600);
    Serial.println( CRC16.kermit(reinterpret_cast<const uint8_t *>(buf.c_str()),(const uint16_t)buf.length()), HEX );
}

Out: 0x2189
https://www.lammertbies.nl out: 0x8921

**Comment by FrankBoesing** [comment]
Maybe. As I wrote in the doc, "Attention: sometimes you'll find byteswapped presentation of result in other implementations)". Just swap the Bytes.
