### ISSUE TITLE
Slim version

### ISSUE THREAD

**Issue by anthonywebb** [FrankBoesing/FastCRC#2]
I am really keen on using this in my arduino project, but it is so large there isnt enough room for my project.  I am specifically looking for a crc16 and dont care about the crc8 or crc32 stuff.  Is there is good way you are aware of to easily trim down the lib a bit?  Thanks!

**Comment by FrankBoesing** [comment]
I am afraid that I can not help there .
The name of the library is " FastCRC " , a reduction of the CRC tables would make it slower and therefore counterproductive...
