### ISSUE TITLE
Use with microcontroller without EEPROM

### ISSUE THREAD

**Issue by mariugul** [FrankBoesing/FastCRC#21]
I'm trying to use this with the nRF52840 from Sparkfun. I cannot get the FastCRC to work: 

> In file included from C:\Users\Mariu\Documents\Arduino\libraries\FastCRC2\FastCRCsw.cpp:38:0:
C:\Users\Mariu\Documents\Arduino\libraries\FastCRC2\FastCRC_tables.h:38:23: fatal error: pgmspace.h: No such file or directory

I'm already using it on Teensy 3.6 with no problems.

**Comment by FrankBoesing** [comment]
Hi, 
it does not use EEPROM.

The errormessages says, there is a file "pgmspace.h" missing. Your nRF52840 seems not to be very Arduino-compatible. Either is it at a unusual location or missing completely.
