### ISSUE TITLE
Library name is already in use (PlatformIO)

### ISSUE THREAD

**Issue by gutierrezps** [FrankBoesing/FastCRC#24]
When installing through PlatformIO Library Manager, the library failed to compile. When I downloaded the zip of the master branch and added manually in my project it worked. <s>Then I noticed that, although library.json and library.properties say version is 1.31, since the commits are not tagged PlatformIO downloaded the last tagged commit/release, 1.0.</s>

In fact, I checked again, and this problem happened because your library has the same name as another. As a consequence, when adding "FastCRC" in lib_deps (inside platformio.ini), the other library that has a smaller ID is installed instead of this one.

The other library: <https://platformio.org/lib/show/3576/FastCRC>
Your library: <https://platformio.org/lib/show/6497/FastCRC>

**Comment by FrankBoesing** [comment]
That other Lib is a copy of mine. No Problem.
