### ISSUE TITLE
SAM3X8E

### ISSUE THREAD

**Issue by Jim-McDonald** [FrankBoesing/FastCRC#4]
Does the Arduino DUE (SAM3X8E) have whatever hardware features you are using for the hardware acceleration?

Or to put it another way, can your hardware CRC library be tweaked to run on the DUE?

**Comment by FrankBoesing** [comment]
No, the hardware-accelerated CRC is implemented for Teensy 3.x (a Freescale ARM M4) only. I don't have a DUE , but i downloaded the Datasheet - this does not mention a CRC unit. I'm not aware of any way to use Hardware-CRC with DUE.

**Comment by Jim-McDonald** [comment]
Thanks for taking a look Frank.

Looks like I'm using your SW implementation then! Many thanks :)
